version: '2'
services:
  nginx:
    build: nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: app_nginx
    ports:
      - "5000:80"
  tomcat:
    build: .
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    container_name: app_tomcat
    links: 
      - mysql-db
    ports:
      - "8080:8080"
  mysql-db:
      image: mysql:5.7
      ports: 
        - "23306:3306"
      volumes: 
        - /tmp/mysql-chata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: "historiaSocialChata"
        MYSQL_USER: "hsocial"
        MYSQL_PASSWORD: "hsocial!123"
        MYSQL_ROOT_PASSWORD: "root!123"
